-- 코드를 입력하세요
SELECT
    BOOK_ID
    , TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') PUBLISHED_DATE
FROM
    BOOK
WHERE
    CATEGORY = '인문'
    AND PUBLISHED_DATE BETWEEN TO_DATE('20210101', 'YYYYMMDD') AND TO_DATE('20211231', 'YYYYMMDD')
ORDER BY 
    PUBLISHED_DATE